<?xml version="1.0" encoding="utf-8"?><Database Name="PrinterStat" Class="PrinterStatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESMI-PC;Initial Catalog=PrinterStat;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PrinterStatConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DeviceType" Member="DeviceType">
    <Type Name="DeviceType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DeviceType_PaperType" Member="PaperType" ThisKey="ID" OtherKey="DeviceTypeID" Type="PaperType" />
      <Association Name="DeviceType_Printer" Member="Printer" ThisKey="ID" OtherKey="DeviceTypeID" Type="Printer" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Job">
    <Type Name="Job">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="PrinterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserTabNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Copies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width_cm" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="Height_cm" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="Width_px" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height_px" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaperTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthorTabNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size_kb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsManual" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Application_Job" Member="Application" ThisKey="ApplicationID" OtherKey="ID" Type="Application" IsForeignKey="true" />
      <Association Name="Employee_Job" Member="Author" ThisKey="AuthorTabNumber" OtherKey="TabNumber" Type="Employee" IsForeignKey="true" />
      <Association Name="Employee_Job1" Member="Employee" ThisKey="UserTabNumber" OtherKey="TabNumber" Type="Employee" IsForeignKey="true" />
      <Association Name="PaperType_Job" Member="PaperType" ThisKey="PaperTypeID" OtherKey="ID" Type="PaperType" IsForeignKey="true" />
      <Association Name="Printer_Job" Member="Printer" ThisKey="PrinterID" OtherKey="ID" Type="Printer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Application">
    <Type Name="Application">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Application_Job" Member="Job" ThisKey="ID" OtherKey="ApplicationID" Type="Job" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="TabNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Job" Member="Job" ThisKey="TabNumber" OtherKey="AuthorTabNumber" Type="Job" />
      <Association Name="Employee_Job1" Member="Job1" ThisKey="TabNumber" OtherKey="UserTabNumber" Type="Job" />
      <Association Name="Employee_Setup" Member="Setup" ThisKey="TabNumber" OtherKey="TabNumber" Type="Setup" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentID" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Department">
    <Type Name="Department">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Employee" ThisKey="ID" OtherKey="DepartmentID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.PaperType" Member="PaperType">
    <Type Name="PaperType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Width_cm" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="Height_cm" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="DeviceTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PaperType_Job" Member="Job" ThisKey="ID" OtherKey="PaperTypeID" Type="Job" />
      <Association Name="DeviceType_PaperType" Member="DeviceType" ThisKey="DeviceTypeID" OtherKey="ID" Type="DeviceType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Printer" Member="Printer">
    <Type Name="Printer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeviceTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrintKindID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SearchString" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InvNumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StatisticsSupported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Printer_Job" Member="Job" ThisKey="ID" OtherKey="PrinterID" Type="Job" />
      <Association Name="Printer_Cartridge" Member="Cartridge" ThisKey="ID" OtherKey="PrinterID" Type="Cartridge" />
      <Association Name="DeviceType_Printer" Member="DeviceType" ThisKey="DeviceTypeID" OtherKey="ID" Type="DeviceType" IsForeignKey="true" />
      <Association Name="PrintKind_Printer" Member="PrintKind" ThisKey="PrintKindID" OtherKey="ID" Type="PrintKind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrintKind" Member="PrintKind">
    <Type Name="PrintKind">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PrintKind_Printer" Member="Printer" ThisKey="ID" OtherKey="PrintKindID" Type="Printer" />
    </Type>
  </Table>
  <Table Name="dbo.Cartridge" Member="Cartridge">
    <Type Name="Cartridge">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrinterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="Printer_Cartridge" Member="Printer" ThisKey="PrinterID" OtherKey="ID" Type="Printer" IsForeignKey="true" />
      <Association Name="CartridgeColor_Cartridge" Member="CartridgeColor" ThisKey="ColorID" OtherKey="ID" Type="CartridgeColor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CartridgeColor" Member="CartridgeColor">
    <Type Name="CartridgeColor">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="CartridgeColor_Cartridge" Member="Cartridge" ThisKey="ID" OtherKey="ColorID" Type="Cartridge" />
    </Type>
  </Table>
  <Table Name="dbo.Setup" Member="Setup">
    <Type Name="Setup">
      <Column Name="MailServer" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Protocol" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TabNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Employee_Setup" Member="Employee" ThisKey="TabNumber" OtherKey="TabNumber" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>